version: "3.9"

services:
  editor:
    image: gorules/editor:latest
    container_name: jdm-editor
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    # Si en Apple Silicon te falla la imagen, agrega:
    # platform: linux/amd64
    profiles: ["editor", "full"]

  zen-sim:
    build:
      context: ./services/simulator
    container_name: jdm-zen-sim
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=production
      - TZ=America/Argentina/Buenos_Aires
      - DATA_DIR=/usr/src/app/data
      - ALLOW_ORIGINS=*
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432/gorules_brms
    volumes:
      - graphs:/usr/src/app/data
    profiles: ["full"]

volumes:
  graphs:
